name: Release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Level of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - test

jobs:
  version_bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_version: ${{ steps.versioning.outputs.NEW_VER }}
      release_tag: ${{ steps.release_tagging.outputs.RELEASE_TAG }}

    steps:
      - name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin
          server-id: 'github'

      - name: Calculate & Set New Version
        id: versioning
        shell: bash
        run: |
          CURRENT_VER=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          
          IFS='.' read -ra ADDR <<< "$CURRENT_VER"
          MAJOR=${ADDR[0]}
          MINOR=${ADDR[1]}
          PATCH=${ADDR[2]}
          
          if [[ "${{ github.event.inputs.bump_type }}" == "major" ]]; then
            NEW_VER="$((MAJOR + 1)).0.0"
          elif [[ "${{ github.event.inputs.bump_type }}" == "minor" ]]; then
            NEW_VER="$MAJOR.$((MINOR + 1)).0"
          elif [[ "${{ github.event.inputs.bump_type }}" == "patch" ]]; then
            NEW_VER="$MAJOR.$MINOR.$((PATCH + 1))"
          else
            NEW_VER="$MAJOR.$MINOR.$PATCH.test"
          fi
          
          echo "NEW_VER=$NEW_VER" >> $GITHUB_OUTPUT
          mvn versions.set -DnewVersion=$NEW_VER -DgenerateBackupPoms=false

      - name: Commit & Push
        if: github.event.inputs.bump-type != 'test'
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.no-reply.github.com"
          
          git commit -am "[ACTION] bump version to ${{ steps.versioning.outputs.NEW_VER }}"
          git push origin main
          
          git tag pom-v${{ steps.versioning.outputs.NEW_VER }}
          git push origin pom-v${{ steps.versioning.outputs.NEW_VER }}

      - name: Squash Merge Into Release
        if: github.event.inputs.bump-type != 'test'
        shell: bash
        run: |
          git fetch origin releases
          git checkout releases
          
          git merge --squash main
          
          git commit -m "Release v${{ steps.versioning.outputs.NEW_VER }}"
          git push origin releases

      - name: Tag Release
        id: release_tagging
        shell: bash
        run:
          echo "RELEASE_TAG=release-v${{ steps.versioning.outputs.NEW_VER }}" >> $GITHUB_OUTPUT
          
          git tag release-v${{ steps.versioning.outputs.NEW_VER }}
          git push origin release-v${{ steps.versioning.outputs.NEW_VER }}

  build:
    needs: version_bump

    name: Build Artifacts
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.version_bump.outputs.release_tag }}
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build Core Library
        shell: bash
        run: mvn -B clean package -DskipTests

      - name: Deploy To Github Packages
        shell: bash
        run: mvn clean deploy

      - name: Package Artifacts
        shell: bash
        run: |
          rm -rf dist
          mkdir -p dist
          
          cp registermaschine-api/target/*.jar dist/
          cp registermaschine-core/target/*.jar dist/
          cp registermaschine-instructions/target/*.jar dist/

      - name: Upload to Single Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version_bump.outputs.release_tag  }}
          files: dist/*
          append_body: true
          make_latest: true
          name: 'Core v${{ needs.version_bump.outputs.new_version }}'
          generate_release_notes: ${{ matrix.os == 'ubuntu-latest' }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
