name: Release
on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Level of version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - test
      dev_type:
        description: 'Level of (dev) version bump, after a release'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  prepare_release:
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.release_version.outputs.NEW_VER }}
      changelog: ${{ steps.changelog.outputs.content }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Setup GraalVM
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: 25

      - name: Download dev-tools Release
        run: |
          mkdir -p dev-tools
          
          curl -L -o dev-tools/ChangelogArchiver.tool \
            https://github.com/TiJ-code/ChangelogTool/releases/tag/releases%2F0.1.0/download/ChangelogArchiver.tool
          curl -L -o dev-tools/ChangelogMarkdownBuilder.tool \
            https://github.com/TiJ-code/ChangelogTool/releases/tag/releases%2F0.1.0/download/ChangelogMarkdownBuilder.tool
          curl -L -o dev-tools/ChangelogPatchParser.tool \
            https://github.com/TiJ-code/ChangelogTool/releases/tag/releases%2F0.1.0/download/ChangelogPatchParser.tool
          curl -L -o dev-tools/ChangelogVersioning.tool \
            https://github.com/TiJ-code/ChangelogTool/releases/tag/releases%2F0.1.0/download/ChangelogVersioning.tool
          
          chmod +x dev-tools/*.tool
          
          mv dev-tools/*.tool .
          
          rm -fr dev-tools

      - name: Apply Release Version
        id: release_version
        if: github.event.inputs.bump_type != 'test'
        run: |
            ./ChangelogVersioning.tool ${{ github.event.inputs.bump_type }}
            
            NEW_VER=$(mvn help:evaluate \
              -Dexpression=project.version \
              -q \
              -DforceStdout)
            
            echo "NEW_VER=$NEW_VER" >> $GITHUB_OUTPUT
            
            echo "Release version: $NEW_VER"

      - name: Build Changelog
        run: |
          ./ChangelogPatchParser.tool
          ./ChangelogMarkdownBuilder.tool
          ./ChangelogArchiver.tool

      - name: Read Changelog
        id: changelog
        run: |
          FILE="changelogs/CHANGELOG.md"
                
          {
            echo 'content<<EOF'
            cat "$FILE"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Commit Release + Tag
        if: github.event.inputs.bump_type != 'test'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.no-reply.github.com"
            
          git add .
            
          git commit -m "release v${{ steps.release_version.outputs.NEW_VER }}"
            
          git tag "release-v${{ steps.release_version.outputs.NEW_VER }}"

      - name: Apply Snapshot Suffix
        if: github.event.inputs.bump_type != 'test'
        run: |
          ./ChangelogVersioning.tool do_suffix

      - name: Commit Next Dev Version
        if: github.event.inputs.bump_type != 'test'
        run: |
          NEXT_DEV_VER=$(mvn help:evaluate \
            -Dexpression=project.version \
            -q \
            -DforceStdout)

          git add .

          git commit -m "prepare next development version ${NEXT_DEV_VER}"

      - name: Push Commits + Tags
        if: github.event.inputs.bump_type != 'test'
        run: |
          git push origin development
          git push origin --tags

  build_and_release:
    needs: prepare_release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: release-v${{ needs.prepare_release.outputs.new_version }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build Maven Project
        run: mvn -B clean package -DskipTests

      - name: Deploy
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Package Artifacts
        run: |
          rm -rf dist
          mkdir dist
          
          cp registermaschine-api/target/*.jar dist/
          cp registermaschine-core/target/*.jar dist/
          cp registermaschine-default-instructions/target/*.jar dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-v${{ needs.prepare_release.outputs.new_version }}
          files: dist/*
          body: ${{ needs.prepare_release.outputs.changelog }}
          make_latest: true
          name: Core v${{ needs.prepare_release.outputs.new_version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}